version: '3'
services:
  geoserver:
    image: registry.antt.gov.br/geoserver/geoserver:2.25.3-2-geoserverpostgis
    container_name: geoserver-postgis-teste
    ports:
      - "8077:8080"
    environment:
      - POSTGRES_JNDI_ENABLED=true
      - POSTGRES_HOST=10.50.2.22
      - POSTGRES_PORT=5444
      - POSTGRES_DB=bd_geo
      - POSTGRES_USERNAME=usr_geo_dev
      - POSTGRES_PASSWORD=A@12345678
      - POSTGRES_JNDI_RESOURCE_NAME=jdbc/postgres
    volumes:
      - ./geoserver_data:/opt/geoserver_data/:Z,ro
    #  - ./additional_libs:/opt/additional_libs:Z # by mounting this we can install libs from host on startup
    healthcheck:
      test: curl --fail "http://localhost:8080/geoserver/web/wicket/resource/org.geoserver.web.GeoServerBasePage/img/logo.png" || exit 1
      interval: 1m
      retries: 3
      timeout: 20s
