version: '3.8'
services:
  geoserver:
    image: osgeo/geoserver:2.25.3
    container_name: geoserver
    ports:
      - "8080:8080"
    environment:
      - "GEOSERVER_DATA_DIR=/opt/geoserver/data_dir"
      - "GEOSERVER_ADMIN_PASSWORD=your_new_password"  # Adicione esta linha com a nova senha
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ./extensions:/opt/geoserver/webapps/geoserver/WEB-INF/lib
volumes:
  geoserver_data:
